#!/bin/bash

apt-get install -y \
ack-grep \
aptitude \
bash-completion \
bind9-host \
curl \
dnsutils \
etckeeper \
git \
htop \
iftop \
lsof \
man-db \
mosh \
dnstop \
passwdqc \
pv \
slurm \
tcpdump \
telnet \
tmux \
unp \
unzip \
vim \
wget \
;
