#!/bin/bash

apt-get install \
ack-grep \
aptitude \
bash-completion \
bind9-host \
curl \
dnsutils \
etckeeper \
git \
htop \
iftop \
lsof \
man-db \
mosh \
dnstop \
openssh-server \
passwdqc \
pv \
silversearcher-ag \
slurm \
tcpdump \
telnet \
tmux \
unp \
unzip \
vim \
wget \
;
