#!/bin/bash

apt-get install -y \
wavemon powertop \
pidgin pidgin-otr pidgin-plugin-pack gfire \
vlc keepass2 gtk-redshift guake gimp \
flashplugin-installer chromium-browser filezilla virtualbox \
lm-sensors hddtemp psensor \
arandr \
pavucontrol \
nautilus-dropbox nautilus-open-terminal \
xpra \
xclip \
wireshark \
preload indicator-cpufreq \
pandoc \
#mtn moviethumbnailer
;
