#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
apt-get update

apt-get install -y \
ack-grep \
autossh \
bash-completion \
bind9-host \
curl \
dnsutils \
etckeeper \
gatling \
git \
htop \
iftop \
lsof \
man-db \
mosh \
nmap \
passwdqc \
pwgen \
slurm \
tcpdump \
telnet \
tmux \
ucspi-tcp \
unp \
unzip \
vim \
wget \
zsh \
;
