#!/bin/bash

# apt-base first

export DEBIAN_FRONTEND=noninteractive
apt-get update

apt-get install -y \
apt-file \
aptitude \
arp-scan \
build-essential \
devtodo \
dnstop \
fail2ban \
ipcalc \
latexdiff \
libssl-dev \
lyx \
munin-node \
nginx \
openssh-client \
openssh-server \
pv \
python-software-properties \
qrencode \
silversearcher-ag \
tsocks \
;
