#!/bin/bash

apt-get install \
apt-file \
autossh \
build-essential \
devtodo \
fail2ban \
ipcalc \
latexdiff \
libssl-dev \
munin-node \
nmap \
python-software-properties \
silversearcher-ag \
tsocks \
ucspi-tcp \
;
