#!/usr/bin/env bash

# apt-base first

export DEBIAN_FRONTEND=noninteractive
apt update

apt install -y \
    apt-file \
    arp-scan \
    autossh \
    cu \
    devtodo \
    dnstop \
    fail2ban \
    gatling \
    iftop \
    ipcalc \
    latexdiff \
    libssl-dev \
    lyx \
    munin-node \
    nginx \
    pv \
    pwgen \
    python-software-properties \
    qrencode \
    rdfind \
    tsocks \
    ucspi-tcp \
;
