#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
apt-get update

apt-get install -y \
ack-grep \
arp-scan \
bash-completion \
bind9-host \
build-essential \
curl \
dnsutils \
etckeeper \
gatling \
git \
htop \
iotop \
lsof \
man-db \
mosh \
nmap \
openssh-client \
openssh-server \
passwdqc \
silversearcher-ag \
slurm \
tcpdump \
telnet \
tmux \
unp \
unzip \
vim \
wget \
whois \
zsh \
;
