#!/bin/bash

apt-get install -y \
wavemon powertop \
pidgin pidgin-otr pidgin-plugin-pack \
vlc \
gtk-redshift \
guake \
gimp \
chromium-browser \
virtualbox \
arandr \
nautilus-dropbox nautilus-open-terminal \
xpra \
xclip \
wireshark \
preload \
;
#lm-sensors hddtemp psensor \
#pavucontrol \
#pandoc \
#indicator-cpufreq \
#filezilla \
#mtn \
