#!/bin/bash

# apt-base first

export DEBIAN_FRONTEND=noninteractive
apt-get update

apt-get install -y \
apt-file \
aptitude \
autossh \
cu \
devtodo \
dnstop \
fail2ban \
iftop \
ipcalc \
latexdiff \
libssl-dev \
lyx \
munin-node \
nginx \
pv \
pwgen \
python-software-properties \
qrencode \
silversearcher-ag \
tsocks \
ucspi-tcp \
;
